### ISSUE TITLE
Punctuation in far east languages

### ISSUE THREAD

**Issue by codingjoe** [flashcode/msgcheck#12]
Hi @flashcode,

it's been a while. Still a waving fan of this package. That being said, I am currently translating things into Japanese and Simplified Chinese. In those languages it is common to use a different character. E.G. in Japanese you would use a [。](https://en.wikipedia.org/wiki/Japanese_punctuation).

Would you be interested in a patch adding support for punctuation for individual locales?

Best,
Joe

**Comment by flashcode** [comment]
Hi Joe,

Sure your contributions are welcome!

I use msgcheck for WeeChat (among others) where there are Japanese translations, so handling the punctuation for these languages would be nice.

Thank you.
