### ISSUE TITLE
Feature request: Ignoring message strings

### ISSUE THREAD

**Issue by maikhoepfel** [flashcode/msgcheck#2]
Hi Sébastien, thank you for a lovely project! I like that it's both useful and the code is so well written. 

We want to add `msgcheck` to our linting at Thermondo as part of a pre-commit hook. But for that to work, we need the option to exclude certain messages from linting - sometimes the trailing dot only does make sense in the source string. 

My suggestion would be to exclude any source string and translation which is prefixed with `# noqa`, as is common in Python land for other linters. 

What do you think? I don't want to promise anything, but there's a good chance we might be able to dedicate time for this if you'd be willing to merge this feature.

**Comment by flashcode** [comment]
Hi @maikhoepfel,

Good idea!
How would the `noa` be set? On a standalone comment line, or inside a "TRANSLATORS" note?
I wonder how you could generate automatically such comment before a string to translate.

**Comment by codingjoe** [comment]
Hi there!

> How would the noa be set? On a standalone comment line, or inside a "TRANSLATORS" note?
> I wonder how you could generate automatically such comment before a string to translate.

I guess that highly depends on which language you are using and how you extract messages form your code. This linter is written in python, but to my understanding it's multi purpose, is it not?

I would recommend just adding the `# noQA` comment manually to the `*.po`-file if need be.

**Comment by amureki** [comment]
@flashcode @maikhoepfel @codingjoe 
Just, FYI, I've started working on this feature yesterday on my free time.

I'll finish when I have spare time, so you can check my implementation.

Open question here: do we want to have a special flag like `--noqa`, to have this check optional?
Or we'll always check for `# noqa` existence, since it won't appear there without someone's intention.

**Comment by codingjoe** [comment]
Nice, I also have two pending PRs. It would be great to get those on their way too, to deal with python format literals.
