### ISSUE TITLE
Feature request: Support several personal files with wordlists

### ISSUE THREAD

**Issue by amureki** [flashcode/msgcheck#5]
Hey @flashcode, thank you for a nice package!

I have a proposal for `-P <file>, --pwl` argument to support several values (comma separated, for example).

In my project, I have several files with exclude words (separate for each language) and selecting all of them would be very handy to be able to work with this check.

What do you think?
I probably, can spend some time, implementing this feature, if you up for it!

**Comment by flashcode** [comment]
Hi @amureki,

Nice idea, but not so easy to implement: the class DictWithPWL (from enchant: https://github.com/rfk/pyenchant/blob/master/enchant/__init__.py#L780) takes just one filename for PWL.

So either we must give None there and add all words manually (from multiple files), either we must build a temporary file that aggragates files and then use it in DictWithPWL.
I'll check which solution is easier to implement.

If you have other ideas, they are welcome.
